version: "3"
services:
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
  
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8001:8001
    volumes:
      - ./app/:/app
      - ./assets/:/assets
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost/fastapi
      
volumes:
  db-data:
    driver: local