version: "3"
services:
  postgres_db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
  
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/fastapi

volumes:
  db-data:
    driver: local
