version: "3"
services:
  postgres:
    image: postgres:15.3 # https://hub.docker.com/_/postgres  # 1
    ports:
      - 5432:5432
    # volumes:
    #   - app-db-data:/var/lib/postgresql/data/pgdata  # 3
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
